name: Run Component and Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ./codesign

      - name: Run tests
        run: npm run test-quick
        working-directory: ./codesign